use_frameworks!

target 'ACNetworking_Example' do
  pod 'ACNetworking', :path => '../'

  pod 'Alamofire'
  pod 'SwiftyJSON
  target 'ACNetworking_Tests' do
    inherit! :search_paths

    
  end
end
